### ISSUE TITLE
Chunk system error: net.buildtheearth.terraminusminus.projection.OutOfProjectionBoundsException

### ISSUE THREAD

**Issue by tf2mandeokyi** [BTE-Germany/TerraPlusMinus#18]
The server crashes when someone tries to teleport with `/minecraft:tp` command to the projection-out-of-bounds area.
It also does that when the same person reconnects to the server after teleporting there.

### Version
`1.3.2`

### Error stack trace
```
[21:40:57 ERROR]: [ChunkTaskScheduler] Chunk system error at chunk (135300,-671030), holder: NewChunkHolder{world=TerraPreGenerated, chunkX=135300, chunkZ=-671030, entityChunkFromDisk=false, lastChunkCompletion={chunk_class=net.minecraft.world.level.chunk.ProtoChunk,status=minecraft:structure_references}, currentGenStatus=minecraft:structure_references, requestedGenStatus=minecraft:full, generationTask=ChunkProgressionTask{class: io.papermc.paper.chunk.system.scheduling.ChunkUpgradeGenericStatusTask, for world: TerraPreGenerated, chunk: (135300,-671030), hashcode: 1823485602, priority: COMPLETING, status: minecraft:biomes, scheduled: true}, generationTaskStatus=minecraft:biomes, priority=NORMAL, priorityLocked=false, neighbourRequestedPriority=IDLE, effective_priority=NORMAL, oldTicketLevel=33, currentTicketLevel=33, totalNeighboursUsingThisChunk=58, fullNeighbourChunksLoadedBitset=0, chunkStatusRaw=0, currentChunkStatus=INACCESSIBLE, pendingChunkStatus=INACCESSIBLE, is_unload_safe=ticket_level, killed=false}, exception:
java.lang.Throwable: java.util.concurrent.CompletionException: java.lang.RuntimeException: net.buildtheearth.terraminusminus.projection.OutOfProjectionBoundsException
        at io.papermc.paper.chunk.system.scheduling.ChunkTaskScheduler.unrecoverableChunkSystemFailure(ChunkTaskScheduler.java:216) ~[paper-1.19.4.jar:git-Paper-550]
        at io.papermc.paper.chunk.system.scheduling.NewChunkHolder.lambda$setGenerationTask$4(NewChunkHolder.java:1672) ~[paper-1.19.4.jar:git-Paper-550]
        at io.papermc.paper.chunk.system.scheduling.ChunkProgressionTask.complete0(ChunkProgressionTask.java:95) ~[paper-1.19.4.jar:git-Paper-550]
        at io.papermc.paper.chunk.system.scheduling.ChunkProgressionTask.complete(ChunkProgressionTask.java:75) ~[paper-1.19.4.jar:git-Paper-550]
        at io.papermc.paper.chunk.system.scheduling.ChunkUpgradeGenericStatusTask.run(ChunkUpgradeGenericStatusTask.java:136) ~[paper-1.19.4.jar:git-Paper-550]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue$PrioritisedTask.executeInternal(PrioritisedThreadedTaskQueue.java:351) ~[paper-1.19.4.jar:git-Paper-550]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadedTaskQueue.executeTask(PrioritisedThreadedTaskQueue.java:118) ~[paper-1.19.4.jar:git-Paper-550]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedThreadPool$PrioritisedThread.pollTasks(PrioritisedThreadPool.java:274) ~[paper-1.19.4.jar:git-Paper-550]
        at ca.spottedleaf.concurrentutil.executor.standard.PrioritisedQueueExecutorThread.run(PrioritisedQueueExecutorThread.java:62) ~[paper-1.19.4.jar:git-Paper-550]
Caused by: java.util.concurrent.CompletionException: java.lang.RuntimeException: net.buildtheearth.terraminusminus.projection.OutOfProjectionBoundsException
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[?:?]
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[?:?]
        at java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1782) ~[?:?]
        at java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:2005) ~[?:?]
        at net.minecraft.world.level.chunk.ChunkGenerator.createBiomes(ChunkGenerator.java:114) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$6(ChunkStatus.java:113) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.world.level.chunk.ChunkStatus.generate(ChunkStatus.java:305) ~[paper-1.19.4.jar:git-Paper-550]
        at io.papermc.paper.chunk.system.scheduling.ChunkUpgradeGenericStatusTask.run(ChunkUpgradeGenericStatusTask.java:83) ~[paper-1.19.4.jar:git-Paper-550]
        ... 4 more
Caused by: java.lang.RuntimeException: net.buildtheearth.terraminusminus.projection.OutOfProjectionBoundsException
        at de.btegermany.terraplusminus.data.TerraConnector.toGeo(TerraConnector.java:31) ~[terraplusminus-1.3.2.jar:?]
        at de.btegermany.terraplusminus.gen.CustomBiomeProvider.getBiome(CustomBiomeProvider.java:30) ~[terraplusminus-1.3.2.jar:?]
        at org.bukkit.generator.BiomeProvider.getBiome(BiomeProvider.java:61) ~[paper-api-1.19.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R3.generator.CustomWorldChunkManager.getNoiseBiome(CustomWorldChunkManager.java:47) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.world.level.chunk.LevelChunkSection.fillBiomesFromNoise(LevelChunkSection.java:331) ~[?:?]
        at net.minecraft.world.level.chunk.ChunkAccess.fillBiomesFromNoise(ChunkAccess.java:480) ~[?:?]
        at net.minecraft.world.level.chunk.ChunkGenerator.lambda$createBiomes$3(ChunkGenerator.java:115) ~[paper-1.19.4.jar:git-Paper-550]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at java.util.concurrent.CompletableFuture.asyncSupplyStage(CompletableFuture.java:1782) ~[?:?]
        at java.util.concurrent.CompletableFuture.supplyAsync(CompletableFuture.java:2005) ~[?:?]
        at net.minecraft.world.level.chunk.ChunkGenerator.createBiomes(ChunkGenerator.java:114) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.world.level.chunk.ChunkStatus.lambda$static$6(ChunkStatus.java:113) ~[paper-1.19.4.jar:git-Paper-550]
        at net.minecraft.world.level.chunk.ChunkStatus.generate(ChunkStatus.java:305) ~[paper-1.19.4.jar:git-Paper-550]
        at io.papermc.paper.chunk.system.scheduling.ChunkUpgradeGenericStatusTask.run(ChunkUpgradeGenericStatusTask.java:83) ~[paper-1.19.4.jar:git-Paper-550]
        ... 4 more
Caused by: net.buildtheearth.terraminusminus.projection.OutOfProjectionBoundsException
```

**Comment by Le4nderS** [comment]
should be fixed in 732fa80
